name: Build project

on:
  push:
    branches:
      - master
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - master
      - main

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform.platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - { platform: StandaloneOSX, itchChannel: "osx" } # Build a macOS standalone (Intel 64-bit)
          #- { platform: StandaloneWindows, itchChannel: "" } # Build a Windows standalone
          - { platform: StandaloneWindows64, itchChannel: "windows" } # Build a Windows 64-bit standalone
          - { platform: StandaloneLinux64, itchChannel: "linux" } # Build a Linux 64-bit standalone
          - { platform: Android, itchChannel: "android" } # Build an Android .apk standalone app
          - { platform: WebGL, itchChannel: "html5" } # WebGL
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false

      - if: matrix.targetPlatform.platform == 'WebGL'
        run: mkdir -p ./build/WebGL/WebGL && touch ./build/WebGL/WebGL/package.json

      - if: matrix.targetPlatform.platform == 'WebGL' ||  matrix.targetPlatform.platform == 'Android' || matrix.targetPlatform.platform == 'StandaloneWindows64'
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform.platform }}
          restore-keys: Library-

      - if: matrix.targetPlatform.platform == 'Android' || matrix.targetPlatform.platform == 'StandaloneOSX'
        uses: jlumbroso/free-disk-space@v1.3.1

      - uses: game-ci/unity-builder@v4
        id: myBuildStep
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          versioning: Semantic
          targetPlatform: ${{ matrix.targetPlatform.platform }}

      - if: matrix.targetPlatform.platform == 'WebGL'
        run: echo '{ "version":"${{ steps.myBuildStep.outputs.buildVersion }}" }' > ./build/WebGL/WebGL/package.json

      - if: matrix.targetPlatform.platform == 'WebGL'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/WebGL/WebGL
          commit-message: Deploy
          single-commit: true

      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform.platform }}
          path: build/${{ matrix.targetPlatform.platform }}

      - if: matrix.targetPlatform.itchChannel != ''
        name: Push ${{ matrix.targetPlatform.platform }} to Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_CREDENTIALS }}
          CHANNEL: ${{ matrix.targetPlatform.itchChannel }}
          ITCH_GAME: luciditydungeon # HERE change this
          ITCH_USER: ebrithilnogare # HERE change this
          PACKAGE: build/${{ matrix.targetPlatform.platform }}
